"""
Django settings for AI_Analyzer project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
import dj_database_url

# -----------------------------------
# 🔹 Base Directory
# -----------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------
# 🔹 Security
# -----------------------------------
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-secret-key-for-development-only')
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Allowed Hosts
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    ALLOWED_HOSTS.append('ai-resume-analyzer-debugger-builder.onrender.com')

# Add localhost for development
if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1', '0.0.0.0'])

# -----------------------------------
# 🔹 Installed Apps
# -----------------------------------
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'ARDAA',
    'resumebuild',
    'accounts',
    'chat',
]

# -----------------------------------
# 🔹 Authentication
# -----------------------------------
AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_REDIRECT_URL = 'ARDAA:index'
LOGOUT_REDIRECT_URL = 'ARDAA:index'
LOGIN_URL = 'accounts:login'

# -----------------------------------
# 🔹 Middleware
# -----------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------------------
# 🔹 URL & Templates
# -----------------------------------
ROOT_URLCONF = 'AI_Analyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ARDAA' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AI_Analyzer.wsgi.application'

# -----------------------------------
# 🔹 Database (PostgreSQL)
# -----------------------------------
# Database Configuration
if 'RENDER' in os.environ:
    # Production database (Render)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Local development database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'ardaa_db',
            'USER': 'ardaa_user',
            'PASSWORD': 'alex**2004',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# -----------------------------------
# 🔹 Password Validation
# -----------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -----------------------------------
# 🔹 Internationalization
# -----------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# -----------------------------------
# 🔹 Static & Media Files
# -----------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# -----------------------------------
# 🔹 Default Auto Field
# -----------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------
# 🔹 Gemini API
# -----------------------------------
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

# -----------------------------------
# 🔹 Simplified Email Configuration
# -----------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Default to console
DEFAULT_FROM_EMAIL = 'ARDAA AI <noreply@ardaa.ai>'

# Production Email Settings (Optional - only if you want welcome emails)
if 'RENDER' in os.environ and os.environ.get('SENDGRID_API_KEY'):
    # Production - SendGrid (Optional)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'apikey'
    EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')
elif 'RENDER' in os.environ:
    # Production but no SendGrid - use console as fallback
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("SENDGRID_API_KEY not set - welcome emails will be logged to console")

# -----------------------------------
# 🔹 Session & CSRF Security
# -----------------------------------
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'ardaa_session'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds

# Security settings for production
if 'RENDER' in os.environ:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'https://ai-resume-analyzer-debugger-builder.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# -----------------------------------
# 🔹 Upload Limits
# -----------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# -----------------------------------
# 🔹 Production Specific Settings
# -----------------------------------
if 'RENDER' in os.environ:
    # Logging
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'accounts': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

# -----------------------------------
# 🔹 Application Specific Settings
# -----------------------------------
# ARDAA AI Specific Settings
ARDAA_SETTINGS = {
    'FREE_RESUME_ANALYSIS_LIMIT': 100,
    'DEFAULT_TOKENS': 100,
    'MAX_FILE_SIZE_MB': 10,
    'SUPPORTED_FILE_TYPES': ['.pdf', '.doc', '.docx', '.txt'],
}

# -----------------------------------
# 🔹 Security Headers (Production)
# -----------------------------------
if 'RENDER' in os.environ:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
