"""
Django settings for AI_Analyzer project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
import dj_database_url

# -----------------------------------
# 🔹 Base Directory
# -----------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------
# 🔹 Security
# -----------------------------------
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-secret-key-for-development-only')
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['ai-resume-analyzer-debugger-builder.onrender.com', 'localhost', '127.0.0.1']

# -----------------------------------
# 🔹 Installed Apps
# -----------------------------------
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'ARDAA',
    'resumebuild',
    'accounts',
    'chat',
]

# -----------------------------------
# 🔹 Authentication
# -----------------------------------
AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_REDIRECT_URL = 'ARDAA:index'
LOGOUT_REDIRECT_URL = 'ARDAA:index'
LOGIN_URL = 'accounts:login'

# -----------------------------------
# 🔹 Middleware
# -----------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------------------
# 🔹 URL & Templates
# -----------------------------------
ROOT_URLCONF = 'AI_Analyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ARDAA' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AI_Analyzer.wsgi.application'

# -----------------------------------
# 🔹 Database (PostgreSQL)
# -----------------------------------
# Database Configuration
if 'RENDER' in os.environ:
    # Production database (Render)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Local development database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'ardaa_db',
            'USER': 'ardaa_user',
            'PASSWORD': 'alex**2004',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# -----------------------------------
# 🔹 Password Validation
# -----------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -----------------------------------
# 🔹 Internationalization
# -----------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# -----------------------------------
# 🔹 Static & Media Files
# -----------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# -----------------------------------
# 🔹 Default Auto Field
# -----------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------
# 🔹 Gemini API
# -----------------------------------
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

# -----------------------------------
# 🔹 Email Configuration (SendGrid)
# -----------------------------------
if 'RENDER' in os.environ:
    # Production - SendGrid
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'apikey'  # ← Literally 'apikey'
    EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')  # ← Your SendGrid API Key
    DEFAULT_FROM_EMAIL = 'ARDAA <noreply@ardaa.com>'
    SERVER_EMAIL = 'ARDAA <noreply@ardaa.com>'
else:
    # Development - Console (emails print to terminal)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'ARDAA <noreply@ardaa.com>'

# -----------------------------------
# 🔹 Session & CSRF Security
# -----------------------------------
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'ardaa_session'

# Security settings for production
if 'RENDER' in os.environ:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'https://ai-resume-analyzer-debugger-builder.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# -----------------------------------
# 🔹 Upload Limits
# -----------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# -----------------------------------
# 🔹 Production Specific Settings
# -----------------------------------
if 'RENDER' in os.environ:
    # Security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Logging
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }
