# Generated by Django 5.2.6 on 2025-09-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usagetracker_delete_usagetraker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagetracker',
            name='tokens_used',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usagetracker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
