# Generated by Django 5.2.6 on 2025-10-13 16:20

import resumebuild.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('experienced', 'Experienced Professional'), ('fresher', 'Fresher/Student')], default='experienced', help_text='Determines which form sections are shown.', max_length=20)),
                ('preview_image', models.ImageField(help_text='Image shown in the template selection carousel.', upload_to=resumebuild.models.get_template_preview_path)),
                ('html_file', models.FileField(upload_to=resumebuild.models.get_template_html_path)),
                ('css_file', models.FileField(blank=True, null=True, upload_to=resumebuild.models.get_template_css_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume Template',
                'verbose_name_plural': 'Resume Templates',
                'ordering': ['name'],
            },
        ),
    ]
